# **Курс "Програмування на мові Python"**

## **Практичне зайняття №9**

### Тема: "Робота з функціями. Локальні та глобальні змінні"

### **Завдання 1 (3 бали)**

**Підрахувати визначник матриці, використовуючи правило перестановок.**

Функція random_matrix() призначена для створення квадратної матриці випадкових чисел. Її змінювати непотрібно.

Приклад використання методу permutations() для створення списку перестановок також подається у комірці з кодом.

1) Створити 3 функції: функцію створення списку перестановок, функцію підрахунку добутків та функцію підрахунку загальної суми.

2) Кожна функція має супроводжуватись рядком документації, що буде коротко описувати її призначення.

3) Розмірність квадратної матриці має вводитись користувачем з клавіатури. Підрахунки виконувати лише в тому разі, якщо користувач введе ціле додатне число.

4) Загальний результат повинен підраховуватись за допомогою композиції функцій.

За бажанням можна перевірити правильність роботи програми за допомогою функції np.linalg.det(a).

In [2]:
import numpy as np
import itertools

def random_matrix(dim):
    """
    The function generates dim x dim array of integers
    between 0 and 10.
    """
    matrix = np.random.randint(10, size = (dim, dim))
    return matrix

def permutations(matrix):
    """
    The function searches for all possible permutations 
    and returns a list of values
    """
    res = []
    matrix_range = [i for i in range(len(matrix))]
    perms = list(itertools.permutations(matrix_range, len(matrix)))
    for i in perms:
        perm = []

        count = 0
        for k in range(len(i)):
            for l in range(k+1, len(i)):
                if i[k] > i[l]:
                    count += 1
        count = 1 if count % 2 == 0 else -1

        perm.append(count)
        for j in i:
            perm.append(matrix[i.index(j), j])
        res.append(perm)
    return res

def multyply(perms):
    """ 
    The function returns the product of permutations
    """
    result = []
    for perm in perms:
        prod = perm.pop(0)
        for i in perm:
            prod *= i
        result.append(prod)
    return result

def sum(prod):
    """
    The function summarizes all elements
    """
    it = 0
    for i in prod:
        it += i
    return it

n = int(input('Enter the size of the square matrix (n > 0): '))

matrix = random_matrix(n)

print('Matrix:')
print(matrix)

det = sum(multyply(permutations(matrix)))
print(f'det = {det}')




Matrix:
[[3 0 2 9 9]
 [9 1 9 4 0]
 [4 1 2 4 6]
 [3 3 4 6 0]
 [4 8 9 7 1]]
det = -5208
